### PR TITLE
Entry exist event state transition #12

### PR DESCRIPTION
**Pull request by arnaud33200**
here is finally my pull request base on the issue #12 

I made a change for the constructor of the FSM, in that case we are sure to call the same constructor from other constructor, I need to trigger the first onEntry for the initial state

I test the build with netBeans 8.2, maybe I need to write some test for that ?

let me know what do I need to change

### CODE REVIEW

**Comment by arnaud33200** [comment]
@developer-x any review done ?

or nobody work on it anymore ?

**Comment by developer-x** [comment]
I'm still working on it when I can.  I've been heads down on my new venture.  Hope to get to this soon.

**Comment by bwzhang2011** [comment]
@developer-x, any update with such issue, hope it could be merged and it's better that statefulj could take scxml standard into action as statefulj lacks the support for standard.

**Comment by developer-x** [comment]
Still haven't had a chance to look into it.  Hadn't heard of the scxml
effort - would be interested in looking into it's compliance.  I hope to
get to this soon.

- Anderw

**Comment by bwzhang2011** [comment]
@developer-x, thanks for view and here came some suggestion from scxml:
1. scxml standard: https://www.w3.org/TR/scxml/
2. scxml apache commons: https://github.com/apache/commons-scxml
3. scxml java: https://github.com/carlos-verdes/scxml-java
as scxml standard seems more open with a lot of languages support and also scxml gui tool, I think long term that statefulj could take it into consideration. by the way, hope the onEntry and onExit could be merged once formed.

**Comment by bwzhang2011** [comment]
@developer-x， any thing update with such issue ?

**Comment by arnaud33200** [comment]
@bwzhang2011 you should do a fork of this project I think, looks like nobody care about this issue. you can grab my pull request if you need

**Comment by arnaud33200** [comment]
I'm going to close it since nobody got back at me...

**Pull request closed without merging**
